[05-Dec-2014 07:26:14 UTC] PHP Fatal error:  Call to undefined method admin\UserBundle\Entity\User::setFacebookId() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 53
[05-Dec-2014 07:26:29 UTC] PHP Fatal error:  Call to undefined method admin\UserBundle\Entity\User::setFacebookId() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 53
[05-Dec-2014 07:35:08 UTC] PHP Fatal error:  Call to undefined method admin\UserBundle\Entity\User::setUserNom() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 58
[05-Dec-2014 07:37:01 UTC] PHP Fatal error:  Call to a member function format() on a non-object in /home/user1025/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/DateType.php on line 53
[05-Dec-2014 07:49:49 UTC] PHP Fatal error:  Call to undefined method HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse::getName() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 59
[05-Dec-2014 07:50:37 UTC] PHP Fatal error:  Call to undefined method HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse::getName() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 60
[05-Dec-2014 07:50:57 UTC] PHP Fatal error:  Call to undefined method HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse::getName() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 60
[05-Dec-2014 07:53:11 UTC] PHP Fatal error:  Call to undefined method HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse::getFirst_name() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 60
[05-Dec-2014 08:01:03 UTC] PHP Fatal error:  Call to undefined method HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\FacebookResourceOwner::getFirstname() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 60
[05-Dec-2014 08:04:10 UTC] PHP Fatal error:  Cannot use object of type HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse as array in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 60
[05-Dec-2014 08:05:46 UTC] PHP Fatal error:  Cannot use object of type HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse as array in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 60
[05-Dec-2014 08:12:07 UTC] PHP Fatal error:  Call to undefined method HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse::getFirstname() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 59
[05-Dec-2014 08:13:17 UTC] PHP Fatal error:  Call to undefined method HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse::getName() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 59
[05-Dec-2014 08:17:24 UTC] PHP Fatal error:  Call to undefined method HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse::getName() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 59
[05-Dec-2014 08:19:11 UTC] PHP Fatal error:  Call to undefined method HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse::getUser() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 59
[05-Dec-2014 08:23:27 UTC] PHP Fatal error:  Call to undefined method HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse::getUser() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 59
[05-Dec-2014 08:24:09 UTC] PHP Fatal error:  Cannot use object of type HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse as array in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 54
[05-Dec-2014 08:24:29 UTC] PHP Fatal error:  Cannot use object of type HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse as array in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 54
[05-Dec-2014 08:27:08 UTC] PHP Fatal error:  Call to undefined method HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse::getUser() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 59
[05-Dec-2014 08:27:48 UTC] PHP Fatal error:  Call to undefined method HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse::getUser() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 59
[05-Dec-2014 08:29:36 UTC] PHP Fatal error:  Call to undefined method HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse::getFavorite_athletes() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 54
[05-Dec-2014 08:30:00 UTC] PHP Fatal error:  Call to undefined method HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse::getFavorite_athletes() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 54
[05-Dec-2014 08:30:39 UTC] PHP Fatal error:  Call to undefined method HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse::getFavorite_athletes() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 54
[05-Dec-2014 08:30:41 UTC] PHP Fatal error:  Class 'admin\UserBundle\Security\Core\User\FOSUBUserProvider' not found in /home/user1025/public_html/app/cache/prod/appProdDebugProjectContainer.php on line 2058
[05-Dec-2014 08:30:48 UTC] PHP Fatal error:  Call to undefined method HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse::getBirthday() in /home/user1025/public_html/src/admin/UserBundle/Security/Core/User/FOSUBUserProvider.php on line 54
[05-Dec-2014 16:02:28 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Yaml\Exception\ParseException' with message 'A YAML file cannot contain tabs as indentation at line 114 (near "			redirect_uris:       "http://nal9ach.com"").' in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Yaml/Parser.php:77
Stack trace:
#0 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(290): Symfony\Component\Yaml\Parser->parse('imports:\n    - ...')
#1 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(42): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->loadFile('/home/user1025/...')
#2 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(106): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/home/user1025/...', NULL)
#3 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFile in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php on line 120
[05-Dec-2014 16:02:52 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Config\Definition\Exception\InvalidConfigurationException' with message 'Unrecognized options "redirect_uris" under "hwi_oauth.resource_owners.google"' in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php:306
Stack trace:
#0 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(263): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array)
#1 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/PrototypedArrayNode.php(269): Symfony\Component\Config\Definition\BaseNode->normalize(Array)
#2 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(263): Symfony\Component\Config\Definition\PrototypedArrayNode->normalizeValue(Array)
#3 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php(298): Symfony\Component\Config\Definition\Bas in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php on line 306
[05-Dec-2014 16:03:25 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Config\Definition\Exception\InvalidConfigurationException' with message 'Unrecognized options "redirect_uris" under "hwi_oauth.resource_owners.google"' in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php:306
Stack trace:
#0 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(263): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array)
#1 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/PrototypedArrayNode.php(269): Symfony\Component\Config\Definition\BaseNode->normalize(Array)
#2 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(263): Symfony\Component\Config\Definition\PrototypedArrayNode->normalizeValue(Array)
#3 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php(298): Symfony\Component\Config\Definition\Bas in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php on line 306
[05-Dec-2014 16:04:54 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Config\Definition\Exception\InvalidConfigurationException' with message 'Unrecognized options "redirect_uris" under "hwi_oauth.resource_owners.google"' in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php:306
Stack trace:
#0 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(263): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array)
#1 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/PrototypedArrayNode.php(269): Symfony\Component\Config\Definition\BaseNode->normalize(Array)
#2 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(263): Symfony\Component\Config\Definition\PrototypedArrayNode->normalizeValue(Array)
#3 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php(298): Symfony\Component\Config\Definition\Bas in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php on line 306
[05-Dec-2014 16:06:23 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Config\Definition\Exception\InvalidConfigurationException' with message 'Unrecognized options "redirect_uri" under "hwi_oauth.resource_owners.google"' in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php:306
Stack trace:
#0 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(263): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array)
#1 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/PrototypedArrayNode.php(269): Symfony\Component\Config\Definition\BaseNode->normalize(Array)
#2 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(263): Symfony\Component\Config\Definition\PrototypedArrayNode->normalizeValue(Array)
#3 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php(298): Symfony\Component\Config\Definition\Base in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php on line 306
[09-Dec-2014 08:04:13 UTC] PHP Fatal error:  Call to a member function getEmail() on a non-object in /home/user1025/public_html/src/front/AnnonceBundle/Controller/AnnonceController.php on line 171
[09-Dec-2014 13:44:13 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Config\Definition\Exception\InvalidConfigurationException' with message 'Unrecognized options "redirect_uri" under "hwi_oauth.resource_owners.google"' in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php:306
Stack trace:
#0 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(263): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array)
#1 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/PrototypedArrayNode.php(269): Symfony\Component\Config\Definition\BaseNode->normalize(Array)
#2 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(263): Symfony\Component\Config\Definition\PrototypedArrayNode->normalizeValue(Array)
#3 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php(298): Symfony\Component\Config\Definition\Base in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php on line 306
[09-Dec-2014 14:06:31 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Yaml\Exception\ParseException' with message 'A YAML file cannot contain tabs as indentation at line 112 (near "				").' in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Yaml/Parser.php:77
Stack trace:
#0 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(290): Symfony\Component\Yaml\Parser->parse('imports:\n    - ...')
#1 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(42): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->loadFile('/home/user1025/...')
#2 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(106): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/home/user1025/...', NULL)
#3 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(102): Symfony\Component\Confi in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php on line 120
[09-Dec-2014 14:06:51 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Yaml\Exception\ParseException' with message 'A YAML file cannot contain tabs as indentation at line 110 (near "			").' in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Yaml/Parser.php:77
Stack trace:
#0 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(290): Symfony\Component\Yaml\Parser->parse('imports:\n    - ...')
#1 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(42): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->loadFile('/home/user1025/...')
#2 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(106): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/home/user1025/...', NULL)
#3 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(102): Symfony\Component\Config in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php on line 120
[09-Dec-2014 14:06:53 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Yaml\Exception\ParseException' with message 'A YAML file cannot contain tabs as indentation at line 110 (near "			").' in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Yaml/Parser.php:77
Stack trace:
#0 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(290): Symfony\Component\Yaml\Parser->parse('imports:\n    - ...')
#1 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(42): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->loadFile('/home/user1025/...')
#2 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(106): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/home/user1025/...', NULL)
#3 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(102): Symfony\Component\Config in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php on line 120
[09-Dec-2014 14:22:06 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Config\Definition\Exception\InvalidTypeException' with message 'Invalid type for path "hwi_oauth.resource_owners.facebook.options". Expected array, but got string' in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php:267
Stack trace:
#0 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(260): Symfony\Component\Config\Definition\ArrayNode->validateType('display:popup')
#1 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php(298): Symfony\Component\Config\Definition\BaseNode->normalize('display:popup')
#2 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(263): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array)
#3 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/PrototypedArrayNode.php(269): Symfony\Component\C in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php on line 267
[09-Dec-2014 14:22:09 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Config\Definition\Exception\InvalidTypeException' with message 'Invalid type for path "hwi_oauth.resource_owners.facebook.options". Expected array, but got string' in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php:267
Stack trace:
#0 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(260): Symfony\Component\Config\Definition\ArrayNode->validateType('display:popup')
#1 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php(298): Symfony\Component\Config\Definition\BaseNode->normalize('display:popup')
#2 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(263): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array)
#3 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/PrototypedArrayNode.php(269): Symfony\Component\C in /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php on line 267
[16-Dec-2014 08:03:01 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/contacte')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\H in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:03:04 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/contacte')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\H in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:04:16 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/contacte')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\H in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:04:59 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/contacte')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\H in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:06:07 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/contacte')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\H in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:06:14 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/contacte')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\H in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:11:31 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/contacte')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\H in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:11:32 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/contacte')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\H in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:12:13 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/contacte')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\H in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:12:19 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/contacte')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\H in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:12:19 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/contacte')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\H in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:12:29 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/contacte')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\H in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:17:45 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/contacte')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\H in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:18:34 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/contacte')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\H in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:18:44 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/contacte')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\H in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:30:20 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/contacte')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\H in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:30:22 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/contacte')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\H in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:33:44 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:34:15 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:34:45 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:34:55 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:35:16 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:35:25 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:35:27 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:35:27 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:35:28 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:35:29 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:37:05 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:37:06 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/annonces/1/0/0...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:37:09 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:37:10 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/annonces/1/0/0...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:37:12 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:37:14 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:37:16 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:37:18 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:37:20 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:37:22 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:37:23 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/annonces/1/0/0...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:39:19 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:39:27 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:39:28 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/annonces/1/ima...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:39:38 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:39:39 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/annonces/1/ima...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:39:42 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:39:43 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/annonces/1/ima...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:39:46 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:45:23 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/qsdsqd')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\Htt in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:46:48 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/qsdsqd')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\Htt in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:46:50 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/qsdsqd')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\Htt in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:46:51 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/qsdsqd')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\Htt in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:46:52 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/qsdsqd')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\Htt in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:46:52 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/qsdsqd')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\Htt in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:46:53 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/qsdsqd')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\Htt in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:51:34 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:53:57 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:54:01 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:56:54 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/qsdsqd')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\Htt in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:56:59 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:57:04 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:57:15 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:57:24 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:57:50 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:59:07 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:59:29 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:59:30 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/annonce/editer...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:59:37 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:59:38 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 08:59:57 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 09:00:16 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/template/image...')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Co in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 09:01:08 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/cdcdcd')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\Htt in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 09:03:53 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/cdcdcd')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\Htt in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[16-Dec-2014 09:32:22 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/user1025/public_html/app/cache/prod/appProdUrlMatcher.php:784
Stack trace:
#0 /home/user1025/public_html/app/cache/prod/classes.php(1352): appProdUrlMatcher->match('/eeeee')
#1 /home/user1025/public_html/app/cache/prod/classes.php(1245): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/user1025/public_html/app/cache/prod/classes.php(1955): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/user1025/public_html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(59): call_user_func(Array, Object(Symfony\Component\Http in /home/user1025/public_html/app/cache/prod/classes.php on line 1971
[22-Dec-2014 11:34:34 UTC] PHP Fatal error:  Call to a member function getFlashBag() on a non-object in /home/user1025/public_html/src/admin/RefBundle/Controller/ServiceController.php on line 217
[22-Dec-2014 11:34:59 UTC] PHP Fatal error:  Call to a member function getFlashBag() on a non-object in /home/user1025/public_html/src/admin/RefBundle/Controller/ServiceController.php on line 217
